# Restart config (ML-Agents 2.0.x) for the FIRST milestone: stable standing / idle imitation.
#
# Intended usage:
# - Set BehaviorParameters -> Behavior Name = MonkeyStand
# - Keep the task simple: flat ground, no beam, one clip (idle/stand).
# - In ImitationAgent, consider:
#   - snapStudentToTeacherOnReset = true
#   - randomizeTeacherPhaseOnReset = true (if clip loops)
#   - applyRandomImpulseOnReset = true, resetImpulseStrength ~ 1-4 (start small)
#   - useExponentialReward = true
#   - aliveRewardPerStep = 0.001
#
# Run:
#   mlagents-learn Assets/Scripts/ppo_monkey_restart_stand.yaml --run-id MonkeyStand_Restart_01
#   (Use --num-envs > 1 if you can run multiple instances.)

behaviors:
  MonkeyStand:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5.0e6
    time_horizon: 64
    summary_freq: 10000
    checkpoint_interval: 100000
    keep_checkpoints: 20
