behaviors:
  MonkeyImitation:
    trainer_type: ppo
    hyperparameters:
      # Fine-tune phase: smaller, safer updates for final convergence.
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1.0e-4
      beta: 3.0e-3
      epsilon: 0.10
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 2.0e7
    checkpoint_interval: 250000
    keep_checkpoints: 50
    time_horizon: 128
    summary_freq: 5000
